package com.fixmycity.complaint;

import java.util.List;
import java.util.UUID;

import com.fixmycity.auth.AuthUser;
import com.fixmycity.common.PageResponse;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
@RequestMapping("/api/complaints")
class ComplaintController {

	/** requestId is generated by the client per form so a retried submission is not duplicated. */
	record SubmitRequest(@NotBlank @Size(min = 5, max = 150) String title,
			@NotBlank @Size(min = 20, max = 5000) String description, @NotBlank @Size(max = 300) String location,
			@NotNull Long categoryId, UUID requestId) {
	}

	record NoteRequest(@NotBlank @Size(max = 2000) String body) {
	}

	record ResolveRequest(@Size(max = 500) String note) {
	}

	record ReopenRequest(@NotBlank @Size(min = 10, max = 500) String reason) {
	}

	record FeedbackRequest(@NotNull @Min(1) @Max(5) Integer rating, @Size(max = 1000) String comment) {
	}

	record AssignmentRequest(Long officerId, Long departmentId, @Size(max = 500) String note) {
	}

	record UpdateRequest(Long categoryId, Priority priority) {
	}

	record CloseRequest(@Size(max = 500) String note) {
	}

	private final ComplaintService service;

	ComplaintController(ComplaintService service) {
		this.service = service;
	}

	@PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
	@PreAuthorize("hasRole('CITIZEN')")
	ResponseEntity<ComplaintDetail> submit(@Valid @ModelAttribute SubmitRequest request,
			@RequestPart(name = "image", required = false) MultipartFile image, @AuthenticationPrincipal AuthUser user) {
		var submission = this.service.submit(user, request.title(), request.description(), request.location(),
				request.categoryId(), request.requestId(), image);
		return ResponseEntity.status(submission.created() ? HttpStatus.CREATED : HttpStatus.OK).body(submission.complaint());
	}

	@GetMapping
	PageResponse<ComplaintSummary> list(@RequestParam(required = false) ComplaintStatus status,
			@RequestParam(required = false) Long categoryId, @RequestParam(required = false) Long departmentId,
			@RequestParam(required = false) Priority priority, @RequestParam(defaultValue = "0") @Min(0) int page,
			@RequestParam(defaultValue = "20") @Min(1) @Max(50) int size, @AuthenticationPrincipal AuthUser user) {
		return this.service.list(user, status, categoryId, departmentId, priority, page, size);
	}

	@GetMapping("/{id}")
	ComplaintDetail get(@PathVariable Long id, @AuthenticationPrincipal AuthUser user) {
		return this.service.get(id, user);
	}

	@PostMapping("/{id}/reopen")
	@PreAuthorize("hasRole('CITIZEN')")
	ComplaintDetail reopen(@PathVariable Long id, @Valid @RequestBody ReopenRequest request,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.reopen(id, user, request.reason());
	}

	@PostMapping("/{id}/feedback")
	@PreAuthorize("hasRole('CITIZEN')")
	ComplaintDetail feedback(@PathVariable Long id, @Valid @RequestBody FeedbackRequest request,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.giveFeedback(id, user, request.rating(), request.comment());
	}

	@PostMapping("/{id}/start")
	@PreAuthorize("hasRole('OFFICER')")
	ComplaintDetail start(@PathVariable Long id, @AuthenticationPrincipal AuthUser user) {
		return this.service.start(id, user);
	}

	@PostMapping("/{id}/notes")
	@PreAuthorize("hasRole('OFFICER')")
	ComplaintDetail addNote(@PathVariable Long id, @Valid @RequestBody NoteRequest request,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.addNote(id, user, request.body());
	}

	@PostMapping(path = "/{id}/proofs", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
	@PreAuthorize("hasRole('OFFICER')")
	ComplaintDetail addProofs(@PathVariable Long id, @RequestPart("images") List<MultipartFile> images,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.addProofs(id, user, images);
	}

	@PostMapping("/{id}/resolve")
	@PreAuthorize("hasRole('OFFICER')")
	ComplaintDetail resolve(@PathVariable Long id, @Valid @RequestBody(required = false) ResolveRequest request,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.resolve(id, user, (request == null) ? null : request.note());
	}

	@PostMapping("/{id}/assignment")
	@PreAuthorize("hasAnyRole('ADMIN', 'OFFICER')")
	ComplaintDetail assign(@PathVariable Long id, @Valid @RequestBody AssignmentRequest request,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.assign(id, user, request.officerId(), request.departmentId(), request.note());
	}

	@PatchMapping("/{id}")
	@PreAuthorize("hasRole('ADMIN')")
	ComplaintDetail update(@PathVariable Long id, @RequestBody UpdateRequest request,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.update(id, user, request.categoryId(), request.priority());
	}

	@PostMapping("/{id}/close")
	@PreAuthorize("hasRole('ADMIN')")
	ComplaintDetail close(@PathVariable Long id, @Valid @RequestBody(required = false) CloseRequest request,
			@AuthenticationPrincipal AuthUser user) {
		return this.service.close(id, user, (request == null) ? null : request.note());
	}

}
